[package]
name = "resy"
version = "0.1.0"

# workspace inheritance
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
regr = { path = "../regr" }

# from workspace
thiserror.workspace = true
