[package]
name = "regr"
version = "0.1.0"
# workspace inheritance
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bumpalo = "3.16"
linked-hash-map = { version = "0.5.6", optional = true }
linked_hash_set = { version = "0.1.5", optional = true }
regex-syntax = "0.8.5"
smallvec = "1"
utf8-ranges = "1"

[features]
hash-map = []
hash-set = []
ordered-hash-map = ["dep:linked-hash-map", "hash-map"]
ordered-hash-set = ["dep:linked_hash_set", "hash-set"]

[dev-dependencies]
pretty_assertions = "1"
