[package]
name = "regr"
version = "0.1.0"
# workspace inheritance
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bumpalo = "~3.17"
cfg-if = "1"
linked-hash-map = { version = "0.5.6", optional = true }
linked_hash_set = { version = "0.1.5", optional = true }

# from workspace
smallvec.workspace = true
thiserror.workspace = true

[features]
hash-map = []
hash-set = []
hash = ["hash-map", "hash-set"]
ordered-hash-map = ["dep:linked-hash-map", "hash-map"]
ordered-hash-set = ["dep:linked_hash_set", "hash-set"]
ordered-hash = ["ordered-hash-map", "ordered-hash-set"]

[dev-dependencies]
pretty_assertions.workspace = true
smallvec.workspace = true
